### ISSUE TITLE
Firefox 50 not launching

### ISSUE THREAD

**Issue by pchorus** [karma-runner/karma-firefox-launcher#61] opened 2016-11-17 15:28 UTC
I updated Firefox to current version 50. Unit tests started from a command prompt are working fine.
If unit tests are run in TeamCity on an agent, I get the following error:
```
[JavaScript Unit Tests] [2016-11-17 16:19:00.167] [WARN] launcher - Firefox have not captured in 60000 ms, killing.
```

I am running grunt with karma 1.3.0, karma-firefox-launcher 1.0.0 and grunt-karma 2.0.0.

**Comment by brandonwshort** [comment] 2016-11-28 16:03
We have run into the same issue running on Windows under the Jenkins service.

**Comment by PaulMilbank** [comment] 2016-12-07 01:41
Running into this issue with both VSTS 2.109 build agent and TeamCity 10.3. Running locally is fine. Running headless through a buildagent fails.

**Comment by jpmnteiro** [comment] 2017-01-13 14:03
Same problem when using TeamCity 10.0.4, but running locally presents no problem

**Comment by gluons** [comment] 2017-01-30 07:31
Me too with **Firefox Developer Edition 53.0a2**.

**Comment by lucamazzanti** [comment] 2017-02-02 14:57
and so? in wich way can i build it with the agent jenkins?

**Comment by RobPierce** [comment] 2017-02-03 12:04
Getting the same problem using Bamboo

**Comment by jpmnteiro** [comment] 2017-02-03 12:06
anyone else has this nagging feeling that not much attention is paid to the karma-*-launchers repos?

**Comment by lucamazzanti** [comment] 2017-02-03 13:06
i downgraded firefox to 49 version and it works. So I will do my tests temporary on an old version.

**Comment by ashes999** [comment] 2017-03-01 14:44
I can confirm that @lucamazzanti 's suggestion fixed the issue for me, too. Downgrading from Firefox 51 to 49 resolved the problem.

**Comment by Ratstail91** [comment] 2017-03-04 10:14
How do you downgrade to 49?

**Comment by ashes999** [comment] 2017-03-04 14:51
@Ratstail91 I uninstalled 51 and googled for "Download firefox 49." I believe I found a copy at FileHippo, which seemed reputable (I don't recall if they bundle crapware/bloatware with it, but if they do, you can opt out of that stuff).

**Comment by jprjr** [comment] 2017-03-04 14:55
All Firefox releases are here: https://ftp.mozilla.org/pub/firefox/releases/

On March 4, 2017 8:51:43 AM CST, "Ashiq A." <notifications@github.com> wrote:
>@Ratstail91 I uninstalled 51 and googled for "Download firefox 49." I
>believe I found a copy at FileHippo, which seemed reputable (I don't
>recall if they bundle crapware/bloatware with it, but if they do, you
>can opt out of that stuff).
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/karma-runner/karma-firefox-launcher/issues/61#issuecomment-284156111

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dignifiedquire** [comment] 2017-03-04 16:29
I've published a new release `1.0.1` with a possible fix. Please let me know if this works

**Comment by Ratstail91** [comment] 2017-03-04 20:23
1.0.1 didn't work, I'm afraid. I can't really install a binary, since this needs to be an automated test and all. I'm doing this for an internship, so there are restrictions to what I can and can't do.

**Comment by Ratstail91** [comment] 2017-03-04 20:26
I'm using this in a headless environment, BTW, on a remote server, so that makes it even harder. If I knew how to install Firefox 49 through npm and point karma launcher at it, that's what I would do. Any advice would be appreciated.

**Comment by dignifiedquire** [comment] 2017-03-04 20:52
FF 51 works fine on OS X for me, so I suspect it's a Windows specific issue. Any details about the version and how things are setup? Does it work on a regular windows machine?

**Comment by Ratstail91** [comment] 2017-03-05 22:29
I'm actually running this on CentOS7. Here's my [package.json, webpack and karma config files](https://gist.github.com/Ratstail91/00db50086d29222d72bab98ad0474ba4).

**Comment by Ratstail91** [comment] 2017-03-06 00:43
I found a solution: opening karma with xvfb provides a virtual frame buffer for Firefox. Now my error is:

    Firefox 45.0.0 (Linux 0.0.0) ERROR
      TypeError: __cov_l4$35_5uOCg4wUM18laBrA.b[3566] is undefined
      at src/bar_graph_panel.jsx:9

So technically, the problem here is solved, I just have another one. Thanks.

**Comment by kevinbosman** [comment] 2017-03-06 07:10
I have confirmed v1.0.1 has resolved the problem for us with 32 bit Firefox 51.0.1, running headless Jenkins on Windows Server 2012 x64. Thanks!

**Comment by n3dst4** [comment] 2017-03-06 11:24
I also confirm that 1.0.1 has fixed the issue for us. We saw this as specifically a **Windows, headless environment** problem (other OSes were always fine, and running on local desktop was always fine.) Thanks, @dignifiedquire.

**Comment by dignifiedquire** [comment] 2017-03-06 11:27
Great to hear, closing this then :)

**Closed by dignifiedquire** 2017-03-06 11:27 UTC

**Comment by pchorus** [comment] 2017-03-07 07:39
Hey everybody,

it works for me as well. Thanks @dignifiedquire for your support.

**Comment by jpmnteiro** [comment] 2017-03-07 08:32
Works for me as well (win7-x64, headless FF 51.0.1), thank you.

**Comment by mrstux** [comment] 2017-03-10 05:41
so, how do we test our tests in multi-process firefox now?

**Comment by devrafalko** [comment] 2017-05-16 21:06
I've just got the same problem (karma-firefox-launcher@1.0.1; windows 10 x64; Firefox 53.0.0), I reinstalled Firefox (to the same latest version 53.0.0), from previous **custom directory** _D:\Programs\bla bla_ to the **default directory** _C:\Program Files\Mozilla Firefox_ and it works ok now, maybe someone will find it helpful

**Comment by Anthony-Mckale** [comment] 2017-06-20 10:27
If you set the FIREFOX_BIN environment variable to your local install (eg if your not admin C:\Users\<USER>\AppData\Local\Mozilla Firefox\firefox.exe)

it should work

Should probably add this to the setup documentation (in core karma docs here --> http://karma-runner.github.io/1.0/config/browsers.html)
